[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cmds = [
  "npm install",
  "pip3 install -r requirements.txt"
]

[phases.build]
cmds = [
  "python3 -m spacy download en_core_web_sm",
  "python3 -m spacy download tr_core_news_sm"
]

[start]
cmd = "node ocrServer.js" 